on:
  push:
    branches:
      - master

name: Code Coverage

jobs:
  grcov:
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2

      - name: Install Stable Toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          override: true

      - name: Cargo Clean
        uses: actions-rs/cargo@v1.0.3
        with:
          command: clean

      - name: Run Tests for Coverage
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --no-fail-fast
        env:
          RUST_LOG: info
          DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/postgres'
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off' # -Cpanic=abort -Zpanic_abort_tests
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off' # -Cpanic=abort -Zpanic_abort_tests
          SMOL_THREADS: 2

      - id: coverage
        uses: actions-rs/grcov@v0.1.6

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # path-to-lcov: './lcov.info'
          path-to-lcov: ${{ steps.coverage.outputs.report }}
